
-- Enable the UUID extension if it's not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create the customers table
CREATE TABLE IF NOT EXISTS customers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    address TEXT,
    loyalty_status TEXT DEFAULT 'None',
    price_band TEXT DEFAULT 'Standard',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    is_account_client BOOLEAN DEFAULT FALSE,
    account_id TEXT,
    sms_opt_in BOOLEAN DEFAULT FALSE,
    email_opt_in BOOLEAN DEFAULT FALSE,
    has_preferred_pricing BOOLEAN DEFAULT FALSE
);

-- Create the staff table
CREATE TABLE IF NOT EXISTS staff (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    login_id TEXT NOT NULL UNIQUE,
    hashed_password TEXT NOT NULL,
    enable_quick_login BOOLEAN DEFAULT FALSE,
    role TEXT NOT NULL DEFAULT 'clerk', -- 'clerk', 'admin', 'super_admin'
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create the catalog_entries table for hierarchical services/items
CREATE TABLE IF NOT EXISTS catalog_entries (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    parent_id UUID REFERENCES catalog_entries(id) ON DELETE SET NULL,
    type TEXT NOT NULL, -- 'category' or 'item'
    price NUMERIC(10, 2), -- Only for items
    description TEXT,
    sort_order INTEGER DEFAULT 0,
    has_color_identifier BOOLEAN DEFAULT FALSE, -- For items
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);


-- Create the orders table
CREATE TABLE IF NOT EXISTS orders (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_number TEXT UNIQUE, -- Should be generated by the app logic
    customer_id UUID REFERENCES customers(id),
    customer_name TEXT, -- Denormalized for convenience
    subtotal_amount NUMERIC(10, 2) NOT NULL,
    cart_discount_amount NUMERIC(10, 2),
    cart_discount_percentage NUMERIC(5, 2),
    cart_price_override NUMERIC(10, 2),
    total_amount NUMERIC(10, 2) NOT NULL,
    status TEXT NOT NULL, -- e.g., 'Received', 'Processing', 'Completed'
    payment_status TEXT, -- e.g., 'Paid', 'Unpaid'
    notes TEXT,
    is_express BOOLEAN DEFAULT FALSE,
    due_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create the order_items table
CREATE TABLE IF NOT EXISTS order_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    service_item_id UUID REFERENCES catalog_entries(id) ON DELETE SET NULL,
    service_name TEXT NOT NULL, -- Denormalized from catalog_entries
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(10, 2) NOT NULL,
    original_unit_price NUMERIC(10, 2),
    item_discount_amount NUMERIC(10, 2),
    item_discount_percentage NUMERIC(5, 2),
    total_price NUMERIC(10, 2) NOT NULL, -- Calculated price after discounts
    notes TEXT,
    has_color_identifier BOOLEAN,
    color_value TEXT
);

-- Create the inventory_items table
CREATE TABLE IF NOT EXISTS inventory_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    unit TEXT NOT NULL,
    low_stock_threshold INTEGER,
    last_restocked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create company_settings table
CREATE TABLE IF NOT EXISTS company_settings (
    id TEXT PRIMARY KEY, -- Use a fixed value like 'global_settings'
    company_name TEXT,
    company_address TEXT,
    company_phone TEXT,
    company_logo_url TEXT,
    vat_tax_id TEXT,
    vat_sales_tax_rate NUMERIC(5, 4),
    include_vat_in_prices BOOLEAN,
    selected_currency TEXT,
    selected_language TEXT,
    available_collection_schedule JSONB,
    available_delivery_schedule JSONB,
    stripe_connect_account_id TEXT,
    enable_platform_fee_pass_through BOOLEAN,
    delivery_fee_base_gbp NUMERIC(10, 2),
    delivery_fee_per_mile_gbp NUMERIC(10, 2),
    delivery_fee_minimum_gbp NUMERIC(10, 2),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create printer_settings table
CREATE TABLE IF NOT EXISTS printer_settings (
    id TEXT PRIMARY KEY, -- Use a fixed value like 'global_printer_settings'
    receipt_printer TEXT,
    customer_receipt_copies TEXT,
    stub_printer TEXT,
    receipt_header TEXT,
    receipt_footer TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create special_offers table
CREATE TABLE IF NOT EXISTS special_offers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    offer_type_identifier TEXT NOT NULL UNIQUE,
    is_active BOOLEAN,
    valid_from TIMESTAMPTZ,
    valid_to TIMESTAMPTZ,
    notes TEXT,
    buy_x_items INTEGER,
    pay_for_y_items INTEGER,
    bundle_item_count INTEGER,
    bundle_price NUMERIC(10, 2),
    spend_threshold NUMERIC(10, 2),
    free_item_description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);


-- Create a transactional function for creating an order with items
DROP FUNCTION IF EXISTS create_order_with_items_tx(text,uuid,text,numeric,numeric,numeric,numeric,numeric,text,text,text,boolean,timestamp with time zone,jsonb);
CREATE OR REPLACE FUNCTION create_order_with_items_tx(
    p_customer_id UUID,
    p_customer_name TEXT,
    p_subtotal_amount NUMERIC,
    p_cart_discount_amount NUMERIC,
    p_cart_discount_percentage NUMERIC,
    p_cart_price_override NUMERIC,
    p_total_amount NUMERIC,
    p_status TEXT,
    p_payment_status TEXT,
    p_notes TEXT,
    p_is_express BOOLEAN,
    p_due_date TIMESTAMPTZ,
    p_items JSONB
)
RETURNS TABLE (
    id UUID,
    order_number TEXT,
    customer_id UUID,
    customer_name TEXT,
    subtotal_amount NUMERIC,
    cart_discount_amount NUMERIC,
    cart_discount_percentage NUMERIC,
    cart_price_override NUMERIC,
    total_amount NUMERIC,
    status TEXT,
    payment_status TEXT,
    notes TEXT,
    is_express BOOLEAN,
    due_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
) AS $$
DECLARE
    new_order_id UUID;
    item JSONB;
BEGIN
    -- Insert the order and get the new ID
    INSERT INTO orders (
        customer_id, customer_name, subtotal_amount, cart_discount_amount,
        cart_discount_percentage, cart_price_override, total_amount, status,
        payment_status, notes, is_express, due_date
    ) VALUES (
        p_customer_id, p_customer_name, p_subtotal_amount, p_cart_discount_amount,
        p_cart_discount_percentage, p_cart_price_override, p_total_amount, p_status,
        p_payment_status, p_notes, p_is_express, p_due_date
    ) RETURNING orders.id INTO new_order_id;

    -- Loop through the items and insert them
    FOR item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        INSERT INTO order_items (
            order_id, service_item_id, service_name, quantity, unit_price,
            original_unit_price, item_discount_amount, item_discount_percentage, total_price,
            notes, has_color_identifier, color_value
        ) VALUES (
            new_order_id,
            (item->>'service_item_id')::UUID,
            item->>'service_name',
            (item->>'quantity')::INTEGER,
            (item->>'unit_price')::NUMERIC,
            (item->>'original_unit_price')::NUMERIC,
            (item->>'item_discount_amount')::NUMERIC,
            (item->>'item_discount_percentage')::NUMERIC,
            (item->>'total_price')::NUMERIC,
            item->>'notes',
            (item->>'has_color_identifier')::BOOLEAN,
            item->>'color_value'
        );
    END LOOP;

    -- Return the newly created order header
    RETURN QUERY SELECT * FROM orders WHERE orders.id = new_order_id;
END;
$$ LANGUAGE plpgsql;


-- Set up Row Level Security (RLS)
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE company_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE printer_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE special_offers ENABLE ROW LEVEL SECURITY;


-- Create policies for RLS
DROP POLICY IF EXISTS "Allow all for anon and authenticated" ON public.customers;
CREATE POLICY "Allow all for anon and authenticated" ON public.customers FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for anon and authenticated" ON public.staff;
CREATE POLICY "Allow all for anon and authenticated" ON public.staff FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for anon and authenticated" ON public.catalog_entries;
CREATE POLICY "Allow all for anon and authenticated" ON public.catalog_entries FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for anon and authenticated" ON public.orders;
CREATE POLICY "Allow all for anon and authenticated" ON public.orders FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for anon and authenticated" ON public.order_items;
CREATE POLICY "Allow all for anon and authenticated" ON public.order_items FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for anon and authenticated" ON public.inventory_items;
CREATE POLICY "Allow all for anon and authenticated" ON public.inventory_items FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for anon and authenticated" ON public.company_settings;
CREATE POLICY "Allow all for anon and authenticated" ON public.company_settings FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for anon and authenticated" ON public.printer_settings;
CREATE POLICY "Allow all for anon and authenticated" ON public.printer_settings FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for anon and authenticated" ON public.special_offers;
CREATE POLICY "Allow all for anon and authenticated" ON public.special_offers FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
